 services:
   api-students:
     build: ./api-students
     ports:
       - 8000:8080
   websimple:
     build: ./websimple
     ports:
       - 8080:80
  webplantilla:
  build: ./webplantilla
  ports:
       - 8081:80

